routes/web.php
Route::get('adminworkstatus/newbankingdelete/{id}', ['as' => 'adminworkstatus.newbankingdelete', 'uses' => 'AdminworkstatusController@newbankingdelete']);
Route::get('workrecord/destroyfederal/{id}',['as'=>'workrecord.destroyfederal','uses'=>'WorkrecordController@destroyfederal']);
Route::get('workrecord/destroystate/{id}',['as'=>'workrecord.destroystate','uses'=>'WorkrecordController@destroystate']);
Route::get('clientsetup/destroyfilling/{id}',['as'=>'clientsetup.destroyfilling','uses'=>'ClientsetupController@destroyfilling']);
Route::get('clientsetup/destroydependent/{id}',['as'=>'clientsetup.destroydependent','uses'=>'ClientsetupController@destroydependent']);
Route::get('clientsetup/destroyincome/{id}',['as'=>'clientsetup.destroyincome','uses'=>'ClientsetupController@destroyincome']);
Route::get('clientsetup/destroyemployee/{empid}',['as'=>'clientsetup.destroyemployee','uses'=>'ClientsetupController@destroyemployee']);
Route::get('clientsetup/clients/destryotherincome/{id2}',['as'=>'clientsetup.destryotherincome','uses'=>'ClientsetupController@destryotherincome']);
Route::post('clientsetup/addweges/{id}',['as'=>'clientsetup.addweges','uses'=>'ClientsetupController@addweges']);
Route::post('clientsetup/addwegesbank/{id}',['as'=>'clientsetup.addwegesbank','uses'=>'ClientsetupController@addwegesbank']);
Route::post('clientsetup/updatedependent',['as'=>'clientsetup.updatedependent','uses'=>'ClientsetupController@updatedependent']);
Route::post('clientsetup/updateincomeweges',['as'=>'clientsetup.updateincomeweges','uses'=>'ClientsetupController@updateincomeweges']);
Route::post('clientsetup/updateotherweges',['as'=>'clientsetup.updateotherweges','uses'=>'ClientsetupController@updateotherweges']);
Route::post('clientsetup/updateexpense',['as'=>'clientsetup.updateexpense','uses'=>'ClientsetupController@updateexpense']);
Route::post('clientsetup/updateintaxation',['as'=>'clientsetup.updateintaxation','uses'=>'ClientsetupController@updateintaxation']);
Route::post('clientsetup/addutilitiesdetail',['as'=>'clientsetup.addutilitiesdetail','uses'=>'ClientsetupController@addutilitiesdetail']);

Route::get('clientsetup/destroyexp/{id}',['as'=>'clientsetup.destroyexp','uses'=>'ClientsetupController@destroyexp']);
Route::get('fscemployee/clients/destroyemployee/{empid}',['as'=>'clients.destroyemployee','uses'=>'employee\ClientsController@destroyemployee']);
Route::get('fscemployee/clients/destryotherincome/{id2}',['as'=>'clients.destryotherincome','uses'=>'employee\ClientsController@destryotherincome']);


Route::get('adminworkstatus/destroyprolic/{id}', ['as' => 'adminworkstatus.destroyprolic', 'uses' => 'AdminworkstatusController@destroyprolic']);
Route::get('adminworkstatus/destroydocument/{id}', ['as' => 'adminworkstatus.destroydocument', 'uses' => 'AdminworkstatusController@destroydocument']);
Route::get('adminworkstatus/destroydocumenttitle/{id}', ['as' => 'adminworkstatus.destroydocumenttitle', 'uses' => 'AdminworkstatusController@destroydocumenttitle']);


Route::get('fac-Bhavesh-0554/workrecord/destroydocumenttitle/{id}',['as'=>'workrecord.destroydocumenttitle','uses'=>'WorkrecordController@destroydocumenttitle']);
Route::get('fac-Bhavesh-0554/workrecord/destroydocument/{id}', ['as' => 'workrecord.destroydocument', 'uses' => 'WorkrecordController@destroydocument']);

Route::get('fscemployee/workrecord/destroydocumenttitle/{id}',['as'=>'workrecord.destroydocumenttitle','uses'=>'WorkrecordController@destroydocumenttitle']);

Route::get('clientsetup/getincomeweges/{id}/{cid}/{cids}', 'Admin\ClientsetupController@getincomeweges')->name('worknew.getincomeweges');


Route::resource('fac-Bhavesh-0554/taxcity','TaxCityController');
Route::resource('fac-Bhavesh-0554/empleave','EmpLeaveController');
Route::resource('fac-Bhavesh-0554/clientsetup','ClientsetupController');
Route::get('/getimagess','ClientsetupController@getimagesssss');
Route::get('/getcertificate','ClientsetupController@getcertificate');
Route::get('/getAdmincertificate','AdminProfileController@getAdmincertificate');

Route::get('/getAdminprolic','AdminProfileController@getAdminprolic');

Route::get('/getaoi','ClientsetupController@getaoi');
Route::get('/getAdminaoi','AdminProfileController@getAdminaoi');
Route::get('/getWorkannual','ClientsetupController@getWorkannual');
Route::get('/getWorkofficer','ClientsetupController@getWorkofficer');



Route::post('adminworkstatus','AdminworkstatusController@store'); 


Route::get('/client_number','ClientsetupController@client_number1');
Route::resource('fac-Bhavesh-0554/cservice','CSServiceController');

Route::resource('fac-Bhavesh-0554/adminupload','AdminUploadController');
Route::resource('fac-Bhavesh-0554/clientupload','ClientUploadController');
Route::resource('fac-Bhavesh-0554/contactinquery','ContactinqueryController');
Route::resource('fac-Bhavesh-0554/linkinquery','LinkinqueryController');
Route::resource('fac-Bhavesh-0554/control','ControlController');
Route::resource('fac-Bhavesh-0554/marque','MarqueController');
Route::resource('fac-Bhavesh-0554/zipcode','ZipcodeController');
Route::resource('fac-Bhavesh-0554/citystate','CitystateController');

Route::resource('fac-Bhavesh-0554/categorys','CategorysController');
Route::resource('fac-Bhavesh-0554/subcategorys','SubcategorysController');
Route::resource('fac-Bhavesh-0554/questionsection','QuestionSectionController');

Route::get('fac-Bhavesh-0554/addressbook','AddressbookController@index');
Route::get('fac-Bhavesh-0554/addressbook/{id}/{type}/edit',['as'=>'addressbook.edit','uses'=>'AddressbookController@edit']); 
Route::resource('fac-Bhavesh-0554/question','QuestionController');
Route::resource('fac-Bhavesh-0554/formationsetup','FormationSetupController');

Route::resource('fac-Bhavesh-0554/license','LicenseController');

Route::resource('fac-Bhavesh-0554/taxation','TaxationSetupController');
Route::get('states/destroylicense/{id}', ['as' => 'states.destroylicense', 'uses' => 'TaxStatesController@destroylicense']);

Route::get('fac-Bhavesh-0554/answer/create/{id}','AnswerController@create');

Route::resource('fac-Bhavesh-0554/answer', 'AnswerController', ['only' => ['store']]);

Route::resource('fac-Bhavesh-0554/rules','RulesController');
Route::get('clientd/clientdelete/{id}', ['as' => 'clientd.clientdelete', 'uses' => 'ClientsetupController@clientdelete']);

Route::get('admind2/admindelete2/{id}/{ccid}', ['as' => 'admind2.admindelete2', 'uses' => 'ClientsetupController@clientdelete1']);


Route::get('review/reviewdelete/{id}', ['as' => 'review.reviewdelete', 'uses' => 'EmployeeController@reviewdelete1']);
Route::get('employee/removeimage/{id}', ['as' => 'employee.removeimage', 'uses' => 'EmployeeController@removeimage']);
Route::get('employee/removeemailrights/{id}/{empid}', ['as' => 'employee.removeemailrights', 'uses' => 'EmployeeController@removeEmailRights']);
Route::get('employee/removeimage1/{id}', ['as' => 'employee.removeimage1', 'uses' => 'EmployeeController@removeimage1']);
Route::get('employee/removeimage2/{id}', ['as' => 'employee.removeimage2', 'uses' => 'EmployeeController@removeimage2']);
Route::get('employee/removeimage3/{id}', ['as' => 'employee.removeimage3', 'uses' => 'EmployeeController@removeimage3']);



Route::get('pay/paydelete/{id}', ['as' => 'pay.paydelete', 'uses' => 'EmployeeController@paydelete1']);
Route::get('admind1/admindelete1/{id}', ['as' => 'admind1.admindelete1', 'uses' => 'AdminProfileController@admindelete1']);
Route::get('admin/adminbankdelete/{id}', ['as' => 'admin.adminbankdelete', 'uses' => 'AdminProfileController@adminbankdelete']);
Route::get('admin/admincarddelete/{id}', ['as' => 'admin.admincarddelete', 'uses' => 'AdminProfileController@admincarddelete']);

Route::get('admin/clientbankdatadelete/{id}', ['as' => 'admin.clientbankdatadelete', 'uses' => 'ClientsetupController@clientbankdatadelete']);
Route::get('admin/clientcarddatadelete/{id}', ['as' => 'admin.clientcarddatadelete', 'uses' => 'ClientsetupController@clientcarddatadelete']);
Route::resource('fac-Bhavesh-0554/emptechnical','EmptechnicalController');

Route::get('admind/admindelete/{id}', ['as' => 'admind.admindelete', 'uses' => 'AdminProfileController@admindelete']);
Route::get('note/notedelete/{id}', ['as' => 'note.notedelete', 'uses' => 'AdminProfileController@notedelete']);

Route::post('fac-Bhavesh-0554/adminprofile/updateformation',['as'=>'adminprofile.updateformation','uses'=>'AdminProfileController@updateformation']);

Route::get('empnote/empnotedelete/{id}', ['as' => 'empnote.empnotedelete', 'uses' => 'EmployeeController@empnotedelete']);
Route::get('taxa/taxadelete/{id}', ['as' => 'taxa.taxadelete', 'uses' => 'PriceController@taxadelete1']);
Route::get('emppay/emppaydelete/{id}', ['as' => 'emppay.emppaydelete', 'uses' => 'EmployeeController@emppaydelete']);
Route::get('empwh/empwhdelete/{id}', ['as' => 'empwh.empwhdelete', 'uses' => 'EmployeeController@empwhdelete']);

Route::get('empreview/empreviewdelete/{id}', ['as' => 'empreview.empreviewdelete', 'uses' => 'EmployeeController@empreviewdelete']);


Route::get('contactinfo/contactdelete/{id}', ['as' => 'contactinfo.contactdelete', 'uses' => 'EmployeeController@contactdelete']);

Route::resource('fac-Bhavesh-0554/servicesprocess','ServiceinquiryController');

Route::resource('fac-Bhavesh-0554/appointment','AppointmentController');
Route::post('/events','CalenderController@event');
Route::resource('fac-Bhavesh-0554/clienttechnical','ClienttechnicalController');
Route::resource('fac-Bhavesh-0554/calender','CalenderController');
Route::resource('fac-Bhavesh-0554/email','EmailController');
Route::resource('fac-Bhavesh-0554/getemail','GetemailController');
Route::get('/cestatus1','CestatusController@cestatus');
Route::get('/getdata','CestatusController@getdata1');
Route::resource('fac-Bhavesh-0554/cestatus','CestatusController');
Route::resource('fac-Bhavesh-0554/insurance','InsController');
Route::resource('fac-Bhavesh-0554/supervisor','SupervisorController');

app/Http/Controllers/Admin/SubcategorysController.php
<?php
namespace App\Http\Controllers\Admin;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Model\Subcategorys;
use App\Model\Categorys;
use DB;
class SubcategorysController extends Controller
{ 
    public function __construct()
    {
      $this->middleware('auth:admin');
    }
  
 
    public function index(Request $request)
    { 
        
        $categorys = DB::table('subcategorys as t1')->select('t1.*','t2.categoryname')
        ->leftJoin('categorys as t2', function($join){ $join->on('t2.subcategoryid', '=', 't1.id');})
        ->orderBy('t1.subcategoryname', 'asc')->get();  
      //$categorys = Subcategorys::paginate(10); 
      return view('fac-Bhavesh-0554.subcategorys.subcategorys',compact(['categorys']));
    }
    
    
    
    // public function create()
    // {
    //     return view('fac-Bhavesh-0554.subcategorys.create');
    // }
    
    
    // public function store(Request $request)
    // {
    //     $this->validate($request,[
    //         'categoryname'=>'required',
    //     ]);
    //     $business = new Categorys;
    //     $business->categoryname = $request->categoryname;
    //     $business->save();
    //     return redirect(route('subcategorys.index'));
    // }

    // public function edit($id)
    // {   
    //     $cat= Categorys::where('id',$id)->first();    
    //     return View('fac-Bhavesh-0554.subcategorys.edit',compact(['cat']));
    // }
    
    // public function update(Request $request, $id)
    // {
    //     $this->validate($request,[
    //         'categoryname'=>'required'
    //     ]);
    //     $business = Categorys::find($id);
    //     $business->categoryname = $request->categoryname;
    //     $business->update();
    //     return redirect(route('subcategorys.index'));
    // }
    
  
    // public function destroy($id)
    // {
    //     Categorys::where('id',$id)->delete();
    //     return redirect(route('subcategorys.index'));
    // }
   
}

resources/views/fac-Bhavesh-0554/subcategorys/create.blade.php
@extends('fac-Bhavesh-0554.layouts.app')
@section('main-content')
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="page-title content-header">
     		<h1>subcategorys</h1>
    </section>
    <!-- Main content -->
    <section class="content">
   <div class="row">
      <div class="col-md-12">
         	<div class="box box-success">
			      <div class="box-header">
      
              <div class="box-tools pull-right">
                
              </div>
            </div>
				<div class="col-md-12">
               <form method="post" action="{{route('subcategorys.store')}}" class="form-horizontal" id="businessname" name="businessname" enctype="multipart/form-data">
                  {{csrf_field()}}
                  <div class="form-group {{ $errors->has('categoryname') ? ' has-error' : '' }}">
                     <label class="control-label col-md-3">Category Name :</label>
                     <div class="col-md-4">
                        <input type="text"  name="categoryname" id="categoryname" class="form-control"  placeholder="category name" >


                        @if ($errors->has('categoryname'))
                        <span class="help-block">
                        <strong>{{ $errors->first('categoryname') }}</strong>
                        </span>
                        @endif
                     </div>
                  </div>




<div class="card-footer">
						    <div class="form-group">
							<label class="control-label col-md-3"></label>
							<div class="col-md-2">
<input class="btn_new_save btn-primary1" type="submit" name="submit" value="Save">
							</div>
							<div class="col-md-2 row">
<a class="btn_new_cancel" href="{{url('fac-Bhavesh-0554/subcategorys')}}">Cancel</a> 
							</div>
						</div>
						  </div>
               </form>
            </div>
         </div>
      </div>
   </div>
       </section>
</div>


@endsection()

resources/views/fac-Bhavesh-0554/subcategorys/edit.blade.php
@extends('fac-Bhavesh-0554.layouts.app')
@section('main-content')
<div class="content-wrapper">
     <!-- Content Header (Page header) -->
    <section class="page-title content-header">
     		<h1>subcategorys</h1>
    </section>
    <!-- Main content -->
    <section class="content">
   <div class="row">
      <div class="col-md-12">
          	<div class="box box-success">
			      <div class="box-header">
            
              <div class="box-tools pull-right">
                
              </div>
            </div>
				<div class="col-md-12">
               <form method="post" action="{{route('subcategorys.update',$cat->id)}}" class="form-horizontal" id="businessname" name="businessname" enctype="multipart/form-data">
                  {{csrf_field()}}{{method_field('PATCH')}}
                 <div class="form-group {{ $errors->has('categoryname') ? ' has-error' : '' }}">
                     <label class="control-label col-md-3">Category Name :</label>
                     <div class="col-md-4">
                        <input type="text"  name="categoryname" id="categoryname" class="form-control" value="{{$cat->categoryname}}" placeholder="category name" >

                        @if ($errors->has('categoryname'))
                        <span class="help-block">
                        <strong>{{ $errors->first('categoryname') }}</strong>
                        </span>
                        @endif
                     </div>
                  </div>




                 <div class="card-footer">
						    <div class="form-group">
							<label class="control-label col-md-3"></label>
							<div class="col-md-2">
<input class="btn_new_save btn-primary1" type="submit" name="submit" value="Save">
							</div>
							<div class="col-md-2 row">
<a class="btn_new_cancel" href="{{url('fac-Bhavesh-0554/subcategorys')}}">Cancel</a> 
							</div>
						</div>
						  </div>
               </form>
            </div>
         </div>
      </div>
   </div>
       </section>
</div>


@endsection()

resources/views/fac-Bhavesh-0554/subcategorys/subcategorys.blade.php
@extends('fac-Bhavesh-0554.layouts.app')

@section('main-content')
<style>
.pagination{ display:none}
</style>
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header page-title" style="height:50px;">
     		<div class="row col-md-12">
     		    <div class="col-md-7" style="text-align:right;">
     		        <h2>List of Sub subcategorys</h2>
     		    </div>
     		    <div class="col-md-5" style="text-align:right;">
     		        <h2>Add / View / Edit</h2>
     		    </div>
     		</div>
    </section>
    <!-- Main content -->
    <section class="content">
	<div class="row">
	<!--<div class="branch">Federal</div>-->
		<div class="col-md-12">
				<div class="box box-success">
			      <div class="box-header" style="padding:5px;">
             
              <div class="box-tools pull-right" style="position:absolute;margin-right:295px;margin-top:7px;z-index:9999;">
                <div class="table-title">
					
						<a href="{{route('subcategorys.create')}}">Add New</a> &nbsp;&nbsp; <a href="{{route('zipcode.create')}}" style="    margin-right: 4px;">Add CSV File</a>
					</div>
              </div>
            </div>
				<div class="col-md-12">
					
					@if ( session()->has('success') )
    <div class="alert alert-success alert-dismissable">{{session()->get('success') }}</div>
                               @endif
					<div class="table-responsive">
						<table class="table table-hover table-bordered" id="sampleTable3">
							<thead>
								<tr>
									<th>No</th>
									<th>Cat Name</th>	
                                    <th>Sub Cat Name</th>	
									<th>Action</th>
								</tr>
							</thead>
							<tbody>
                                @foreach($categorys as $bus)
                          
								<tr>
									<td style="text-align:center;">{{$loop->index + 1}}</td>
									<td style="text-align:center;">{{$bus->categoryname}}</td>
									<td style="text-align:center;">{{$bus->subcategoryname}}</td>
									

	<td style="text-align:center;">
										<a class="btn-action btn-view-edit" href="{{route('subcategorys.edit', $bus->id)}}"><i class="fa fa-edit"></i></a>
                                        <form action="{{ route('subcategorys.destroy',$bus->id) }}" method="post" style="display:none" id="delete-id-{{$bus->id}}">
                                        {{csrf_field()}} {{method_field('DELETE')}}
                                        </form>
                                        
										<a class="btn-action btn-delete" onclick="if(confirm('Are you sure, You want to delete this record ?'))
                                                                                  {event.preventDefault();document.getElementById('delete-id-{{$bus->id}}').submit();} else{event.preventDefault();}" href=""><i class="fa fa-trash"></i></a>
									</td>
								</tr>
								@endforeach

							</tbody>
						</table>
{!! $categorys->links('pagination') !!}
					</div>
				</div>
			</div>
		</div>
		
	</div>
		    </section>
</div>
	
@endsection()