routes/web.php
Route::post('/checkclientfile','CustomerController@checkclientfile');

Route::group(['namespace'=>'Admin'],function()
{
Route::resource('fac-Bhavesh-0554/language','LanguageController');
Route::resource('fac-Bhavesh-0554/holiday','HolidayController');

Route::resource('fac-Bhavesh-0554/ethnic','EthnicController');

Route::resource('fac-Bhavesh-0554/submissionreq','SubmissionController');

Route::match(['get', 'post'], 'ajax-image-upload/{id}', 'EmployeeController@ajaxImage');
Route::delete('ajax-remove-image/{filename}', 'EmployeeController@deleteImage');
Route::match(['get', 'post'], 'ajax-image-upload1/{id}', 'EmployeeController@ajaxImage1');
Route::delete('ajax-remove-image1/{filename}', 'EmployeeController@deleteImage1');
Route::match(['get', 'post'], 'ajax-image-upload2/{id}', 'EmployeeController@ajaxImage2');
Route::delete('ajax-remove-image2/{filename}', 'EmployeeController@deleteImage2');
Route::match(['get', 'post'], 'pfid_upload/{id}', 'EmployeeController@pfid_upload1');
Route::match(['get', 'post'], 'pfid_upload2/{id}', 'EmployeeController@pfid_upload2');
Route::match(['get', 'post'], 'photo_upload/{id}', 'EmployeeController@photo_upload2');
Route::delete('pfid_upload/{filename}', 'EmployeeController@pfid_upload1');

Route::resource('fac-Bhavesh-0554/employee','EmployeeController');
Route::resource('fac-Bhavesh-0554/clientemployee','ClientemployeeController');
Route::post('fac-Bhavesh-0554/login', 'Auth\LoginController@login');         
Route::resource('fac-Bhavesh-0554/business','BusinessController');
Route::resource('fac-Bhavesh-0554/language','LanguageController');

Route::resource('fac-Bhavesh-0554/bankingsetup','BankingsetupController');

Route::resource('fac-Bhavesh-0554/statetax','StatetaxController');
Route::resource('fac-Bhavesh-0554/businesscard','BusinesscardController');
Route::resource('fac-Bhavesh-0554/letterhead','LetterheadController');

Route::resource('fac-Bhavesh-0554/accountcode','AccountcodeController');
Route::resource('fac-Bhavesh-0554/emailsetup','EmailSetupController');
Route::resource('fac-Bhavesh-0554/howtodo','HowtodoController');
Route::get('/faderal','AdminProfileController@getfaderal');

Route::get('/gemails','EmailController@getemails');
Route::get('fac-Bhavesh-0554/getemailList/{id}','EmailController@getEmailList');

Route::get('/getfaderalsss','AdminProfileController@getfaderalss');
Route::resource('fac-Bhavesh-0554/adminprofile','AdminProfileController');
Route::get('getlegalname','AdminProfileController@getlegalname');
Route::get('/getforms','AdminProfileController@getformss');
Route::get('/getimage','AdminProfileController@getimages');

Route::get('/history1','AdminProfileController@history');

Route::get('/clientid','MessageController@clientname12');
Route::resource('fac-Bhavesh-0554/msg','MessageController');
Route::resource('fac-Bhavesh-0554/msgout','MessageoutController');
Route::resource('fac-Bhavesh-0554/schedulesetup','SchedulesetupController');
Route::resource('fac-Bhavesh-0554/changepassword','ChangePasswordController');
Route::resource('fac-Bhavesh-0554/business-add-new','BusinessController');
Route::resource('fac-Bhavesh-0554/language-add-new','LanguageController');
Route::resource('fac-Bhavesh-0554/ethnic-add-new','EthnicController');
Route::resource('fscemployee/msgoutemp','MessageoutempController');

Route::resource('fac-Bhavesh-0554/businesscategory','CategoryController');    
Route::resource('fac-Bhavesh-0554/business-category-add-new','CategoryController');
Route::resource('fac-Bhavesh-0554/business-brand','BusinessBrandController');
Route::get('/getRequest','BusinessBrandController@getcategory');


Route::get('/getRequestbrand','BusinessBrandController@getbrand');
Route::resource('fac-Bhavesh-0554/employment','EmploymentContoller');
Route::get('deletecon/deletecon1', ['as' => 'delete1.delete', 'uses' => 'CustomerController@deletecon']);
Route::resource('fac-Bhavesh-0554/ee-schedule','EmployeescheduleController');
Route::post('fac-Bhavesh-0554/typeof',['as'=>'typeof.typeofentity','uses'=>'TaxFederalController@entityies']);
Route::get('/salestax','CustomerController@salestax1');
Route::get('/salestaxacc','CustomerController@salestaxacc');

Route::get('/getbankdata','CustomerController@getbankdata');
Route::get('/getrouting','ClientsetupController@getrouting');



Route::get('/salestaxations','CustomerController@salestaxations');

Route::get('/salestaxpay','CustomerController@salestaxpay');


Route::get('/getlanguage','CustomerController@getlanguage');
Route::get('/getsecondlanguage','CustomerController@getsecondlanguage');

Route::get('/lock','CustomerController@locked2');
Route::get('/taxlock','CustomerController@taxlocked2');
Route::get('/updateemployee','CustomerController@updateemployee');
Route::get('/updateacccheckby','CustomerController@updateacccheckby');
Route::get('/taxupdateacccheckby','CustomerController@taxupdateacccheckby');


Route::get('/taxupdateemployee','CustomerController@taxupdateemployee');


Route::get('bank/banks/{id}', ['as' => 'bank.banks', 'uses' => 'ClientsetupController@banks']);
Route::get('bank1/banks1/{id}', ['as' => 'bank1.banks1', 'uses' => 'ClientsetupController@banks1']);




Route::get('notes/notedelete/{id}', ['as' => 'notes.notedelete', 'uses' => 'CustomerController@notedelete']);
Route::get('locked/lockeddelete/{id}', ['as' => 'locked.lockdelete', 'uses' => 'CustomerController@locksdelete']);
Route::get('howtodo1/howtododelete/{id}', ['as' => 'howtodo1.howtododelete', 'uses' => 'HowtodoController@howtodo11delete']);
Route::resource('fac-Bhavesh-0554/business-brand-category','BusinessBrandCategoryController');
Route::resource('fac-Bhavesh-0554/business-brand-category-add-new','BusinessBrandCategoryController');

Route::get('/getEEResponsibility','CustomerController@getEEResponsibility');

Route::resource('fac-Bhavesh-0554/customer','CustomerController');

Route::resource('fac-Bhavesh-0554/vendor','VendorController');
Route::post('fac-Bhavesh-0554/product',['as'=>'product.productss','uses'=>'VendorController@productss']);

Route::post('fac-Bhavesh-0554/positions',['as'=>'position.positions','uses'=>'VendorController@positions']);
Route::post('fac-Bhavesh-0554/team',['as'=>'team.teams','uses'=>'VendorController@teams']);
Route::post('fac-Bhavesh-0554/utilities',['as'=>'utilities.utilitiess','uses'=>'VendorController@utilitiess']);
Route::post('fac-Bhavesh-0554/insurances',['as'=>'insurance.insurances','uses'=>'VendorController@insurances']);
Route::post('fac-Bhavesh-0554/otherbusiness',['as'=>'otherbusiness.otherbusinesss','uses'=>'VendorController@otherbusinesss']);

Route::post('fac-Bhavesh-0554/relatednames',['as'=>'relatedname.relatednames','uses'=>'VendorController@relatednames']);
Route::post('fac-Bhavesh-0554/notesrelateds',['as'=>'notesrelated.notesrelateds','uses'=>'VendorController@notesrelateds']);
Route::post('fac-Bhavesh-0554/profession',['as'=>'profile.profession','uses'=>'VendorController@profession']);

Route::get('fac-Bhavesh-0554/professionDelete', ['as' => 'profile.professionDelete', 'uses' => 'VendorController@professionDelete']);

Route::post('fac-Bhavesh-0554/work',['as'=>'work.workcategorys','uses'=>'WorktodoController@workcategorys']);
Route::post('fac-Bhavesh-0554/teamadd',['as'=>'work.teamadd','uses'=>'WorktodoController@teamadd']);

Route::post('fac-Bhavesh-0554/bankadd',['as'=>'bank.bankadd','uses'=>'ClientsetupController@bankadd']);
Route::post('fac-Bhavesh-0554/taxadd',['as'=>'tax.taxadd','uses'=>'ClientsetupController@taxadd']);
Route::post('fac-Bhavesh-0554/dependentadd',['as'=>'dependent.dependentadd','uses'=>'ClientsetupController@dependentadd']);

Route::post('fac-Bhavesh-0554/incomeadd',['as'=>'income.incomeadd','uses'=>'ClientsetupController@incomeadd']);
Route::post('fac-Bhavesh-0554/cardadd',['as'=>'card.cardadd','uses'=>'ClientsetupController@cardadd']);
Route::post('fac-Bhavesh-0554/expenseadd',['as'=>'expense.expenseadd','uses'=>'ClientsetupController@expenseadd']);

Route::get('products/removeproduct', ['as' => 'removeproduct.removeproducts', 'uses' => 'VendorController@removeproducts']);
Route::get('position/removeposition', ['as' => 'removeposition.removepositions', 'uses' => 'VendorController@removepositions']);
Route::get('teams/removeteam', ['as' => 'removeteam.removeteams', 'uses' => 'VendorController@removeteams']);
Route::get('utilities/removeutilities', ['as' => 'removeutilities.removeutilitiess', 'uses' => 'VendorController@removeutilitiess']);
Route::get('insurance_company/removeinsurance', ['as' => 'removeinsurance.removeinsurances', 'uses' => 'VendorController@removeinsurances']);
Route::get('utilities/removebusiness', ['as' => 'removebusiness.removebusinesss', 'uses' => 'VendorController@removebusinesss']);


Route::get('/getAccountcode','VendorController@Accountcode1');
Route::resource('fac-Bhavesh-0554/customerconvert','ClientconvertController');
Route::resource('fac-Bhavesh-0554/logo','LogoController');
Route::post('getclick','ClientconvertController@checkclient');
Route::post('fetch1','WorkrecordController@fetch1');
Route::post('fetch1','WorknewController@fetch1');


Route::post('checkclientemail1','ClientconvertController@checkclientemail');
Route::get('/getRequest','CustomerController@getcategory');
Route::get('/getRequests','CustomerController@getcategory');

Route::get('/getClientfilenameid','CustomerController@getfilenameid');


Route::get('/getnaics','CustomerController@getnaics');

Route::get('/getClientfilename','CustomerController@getfilename');
Route::get('/getAdminlic','AdminProfileController@getfilename');

Route::get('/getAdminlicprofession','AdminProfileController@getfilenameprofession');

Route::get('/getCountytaxstate','TaxStateController@getcountytax');
Route::get('/getCountycodetax','TaxStateController@getcountycodes');
Route::get('/getDocumentdata','AdminworkstatusController@getdocument');
Route::get('/getAdminlicensedata','AdminworkstatusController@getbuslicense');

resources/views/fac-Bhavesh-0554/businesscategory/business-category-add-new.blade.php
@extends('fac-Bhavesh-0554.layouts.app')

@section('main-content')
<div class="content-wrapper">
 <!-- Content Header (Page header) -->
    <section class="page-title content-header">
     		<h1>Business Category</h1>
    </section>
    <!-- Main content -->
    <section class="content">
	
	<div class="row">
		<div class="col-md-12">
				<div class="box box-success">
			      <div class="box-header">
              
              <div class="box-tools pull-right">
                
              </div>
            </div>
				<div class="col-md-12">
					<form method="post" class="form-horizontal" id="" action="{{route('businesscategory.store')}}" enctype="multipart/form-data">
					{{csrf_field()}}
						<div class="form-group {{ $errors->has('bussiness_name') ? ' has-error' : '' }}">
							<label class="control-label col-lg-3 col-md-4">Business Name :</label>
							<div class="col-lg-4 col-md-8">
								<select class="form-control" id="bussiness_name" name="bussiness_name">
                                    <option value=''>Please select Business</option>
                                    @foreach($business as $bus)								
									<option value='{{$bus->id}}'>{{$bus->bussiness_name}}</option>								
                                    @endforeach
								</select>
                                                                       @if ($errors->has('bussiness_name'))
										<span class="help-block">
											<strong>{{ $errors->first('bussiness_name') }}</strong>
										</span>
									@endif
							</div>
						</div>
						
						<div class="form-group {{ $errors->has('business_cat_name') ? ' has-error' : '' }}">
							<label class="control-label col-lg-3 col-md-4">Business Category :</label>
							<div class="col-lg-4 col-md-8">
								<input name="business_cat_name" type="text" id="business_cat_name" class="form-control" value="" />                                                   @if ($errors->has('business_cat_name'))
									<span class="help-block">
										<strong>{{ $errors->first('business_cat_name') }}</strong>
									</span>
								@endif
							</div>
						</div>
    <div class="naicss">
               
       <div class="form-group">
       <label class="col-lg-3 col-md-4 col-xs-12 left_991 control-label">NAICS / SIC Code: </label>
           <div class="col-lg-2 col-md-3 col-xs-4 fsc-element-margin">
           <input type="text" class="form-control fsc-input naics" id="" name="naics" placeholder="NAICS" value="">
           </div>
           
           <div class="col-lg-2 col-md-3 col-xs-4 fsc-form-col">
               <div class="dropdown">
               <input type="text" class="form-control fsc-input sic" placeholder="SIC" id="" name="sic" value="">
               
               </div>
           </div>
           
           <!--<div class="col-lg-4 col-md-12 col-sm-12 col-xs-12 fsc-element-margin">
                <input type="text" class="form-control fsc-input" placeholder="Search" id="" name="" value="">
           </div>!-->
           
           <div class="col-lg-2 col-md-2 col-xs-4 fsc-element-margin">
               <!--<input type="button" class="add-row btn btn-primary" value="Go to Link">-->
               <a href="https://www.naics.com/code-search/" target="_blank" class="add-row btn btn-primary">Go to Link</a>
           </div>
       </div>

           </div>
       						
						<div class="form-group {{ $errors->has('business_cat_image') ? ' has-error' : '' }}">
							<label class="control-label col-lg-3 col-md-4">Business Category Image :</label>
							<div class="col-lg-4 col-md-8">
							    <label class="file-upload btn btn-primary">
		                Browse for file ... <input name="business_cat_image" style="opecity:0" placeholder="Upload Service Image" id="business_cat_image" type="file">
		            </label>
							    
							
@if ($errors->has('business_cat_image'))
										<span class="help-block">
											<strong>{{ $errors->first('business_cat_image') }}</strong>
										</span>
									@endif
							</div>
						</div>
						<div class="form-group {{ $errors->has('link') ? ' has-error' : '' }}">
							<label class="control-label col-lg-3 col-md-4">Url :</label>
							<div class="col-lg-4 col-md-8">
								<input name="link" type="text" value="" id="link" class="form-control"/>
@if ($errors->has('link'))
										<span class="help-block">
											<strong>{{ $errors->first('link') }}</strong>
										</span>
									@endif
							</div>
						</div>
						<div class="card-footer">
						    <div class="form-group">
							<label class="control-label col-lg-3 col-md-4"></label>
							<div class="col-xs-2" style="width:155px;">
<input class="btn_new_save btn-primary1 primary1" type="submit" id="primary1" name="submit" value="Save">
							</div>
							<div class="col-xs-2" style="width:155px;">
<a class="btn_new_cancel" href="{{url('fac-Bhavesh-0554/businesscategory')}}">Cancel</a> 
							</div>
						</div>
						  </div>
					
					
						
					</form>
				</div>
			</div>
		</div>
	</div>
	 </section>
</div>
<script>
      $(".naics").mask("999999");
      $(".sic").mask("9999");
      
 
</script>
@endsection()

resources/views/fac-Bhavesh-0554/businesscategory/businesscategory.blade.php
@extends('fac-Bhavesh-0554.layouts.app')
@section('main-content')
<style>
label{float:left;}
.box-tools{
        position:absolute !important;
        margin-top: 7px !important;
        margin-right: 150px !important;
    }
    .page-title {
    display: -ms-flexbox;
    -ms-flex-align: center;
    align-items: center;
    -ms-flex-pack: justify;
    justify-content: space-between;
    -ms-flex-direction: row;
    flex-direction: row;
    padding: 8px 18px !important;
    box-shadow: 0 1px 2px rgba(0,0,0,.1);
    background-color: #D6EBFA !important;
    text-align: center;
}
.buttons-pdf {
    font-size: 0px !important;
    border-radius: 3px;
    padding: 8px 10px !important;
    background: #fff !important;
    border-color: #c6c6c6  !important;
    color:red !important;
}
.buttons-print {
    font-size: 0px !important;
    border-radius: 3px;
    padding: 8px 10px !important;
    background: #3c8dbc !important;
            border-color: #367fa9 !important;
}
.buttons-excel{
    font-size:0px !important;
    border-radius: 3px;
    padding: 8px 10px !important;
    background: #00a65a !important;
    border-color: #008d4c !important;
}
.buttons-excel:hover{
     background: #008d4c !important;
}
.buttons-pdf:hover{
     background: #f6f6f6  !important;
}
.buttons-print:hover{
     background: #367fa9 !important;
}
.fa{
    font-size: 16px !important;
}
.content-header.page-title h2 {
    margin: 0;
    font-size: 22px!important;
    font-weight: 600!important;
    color: #222!important;
}
@media only screen and (max-width: 991px){
    .table-title a {
        margin-top: 0px !important; 
        margin-right: -10px !important;
    }
}
@media only screen and (max-width: 860px){
    .box-header>.box-tools{
        position: relative !important;
        margin-right: 5px !important;
        margin-top: 0px !important;
    }
}
@media only screen and (max-width: 490px){
    div.dataTables_wrapper div.dataTables_filter{
        width: 100%;
        display: flex;
    }
    div.dataTables_wrapper div.dataTables_filter label{
        width: 84%;
    }
    .table-title a {
        margin-top: -34px !important;
        margin-right: 10px !important;
    }
    .box-header>.box-tools {
        position: absolute !important;
        margin-top: 51px !important;
        margin-right: 120px !important;
    }
    .box-header {
        padding: 10px !important;
    }
}
</style>
<div class="content-wrapper">

	 <!-- Content Header (Page header) -->
   
    <section class="content-header page-title" >
     		<div class="" style="margin-top:5px;padding-right:0px;">
     		    <div class="" style="text-align:center;">
     		        <h2>List of Business Category <span class="right_title" style="text-align:right;padding-right: 20px !important;position: absolute;right: 0;">Add / View / Edit</span></h2>
     		    </div>
     		    
     		</div>
    </section>
    <!-- Main content -->
    <section class="content">
	<div class="row">
	
		<div class="col-md-12">
				<div class="box box-success">
			      <div class="box-header" style="padding:0px;">
              
                  <div class="box-tools pull-right" style="position: absolute;margin-right: 132px;margin-top:7px;z-index:9999;">
                    <div class="table-title">
					
						<a href="{{route('businesscategory.create')}}">Add New</a>
					</div>
              </div>
            </div>
				<div class="col-md-12">
				
					@if ( session()->has('success') )
    <div class="alert alert-success alert-dismissable">{{session()->get('success') }}</div>
                               @endif
					<div class="table-responsive">
						<table class="table table-hover table-bordered" id="example">
						
							<thead>
								<tr>
									<th>No</th>
									<th>Business</th>
									<th>Business Category</th>
									<th>NAICS</th>
									<th>SIC</th>
									
									<th>Business Image</th>
									<th>Action</th>
								</tr>
							</thead>
							
							<tbody>
                                @foreach($category as $cat)
								<tr>
									<td style="text-align:center;">{{$loop->index+1}}</td>
									<td> {{$cat->bussiness_name}}</td>
									<td>{{$cat->business_cat_name}}</td>
									<td>{{$cat->naics}}</td>
									<td>{{$cat->sic}}</td>
									
									<td style="text-align:center;"><img style="width: 100px;" src="https://financialservicecenter.net/public/category/{{$cat->business_cat_image}}" class="small-image" alt="" /></td>
									<td style="text-align:center;">
										<a class="btn-action btn-view-edit" href="{{route('businesscategory.edit', $cat->cid)}}"><i class="fa fa-edit"></i></a>
                                        <form action="{{ route('businesscategory.destroy',$cat->cid) }}" method="post" style="display:none" id="delete-id-{{$cat->cid}}">
                                        {{csrf_field()}} {{method_field('DELETE')}}
                                        </form>
										<a class="btn-action btn-delete" href="#"onclick="if(confirm('Are you sure, You want to delete this record ?'))
                                                                                  {event.preventDefault();document.getElementById('delete-id-{{$cat->cid}}').submit();} else{event.preventDefault();}"><i class="fa fa-trash"></i></a>
									</td>
								</tr>
								@endforeach
							</tbody>
							
						</table>
					</div>
				</div>
			</div>
		</div>
		
	</div>
	 </section>
<!--</div>-->
<script>
$(document).ready(function() {
    var table = $('#example').DataTable( {
        dom: 'Bfrtlip',
    "columnDefs": [ {
            "searchable": true,
            "orderable": true,
            "targets": 0
        } ],
        "order": [[ 0, 'asc' ]],
        buttons: [
                 {
                extend:    'copyHtml5',
                text:      '<i class="fa fa-files-o"></i> &nbsp; Copy',
                titleAttr: 'Copy',
                title: $('h3').text(),
                  exportOptions: {
        columns: [0,1, 2, 3,4,5], // Only name, email and role
    }
            },
            {
                extend:    'excelHtml5',
                text:      '<i class="fa fa-file-excel-o"></i>&nbsp; Excel',
               titleAttr: 'Excel',
                title: $('h3').text(),
                 customize: function( xlsx ) {
                var sheet = xlsx.xl.worksheets['sheet1.xml'];
 $('row c', sheet).attr('s', '51');
            },
                  exportOptions: {
        columns: [0,1, 2, 3,4,5], // Only name, email and role
    }
            },
            {
                extend:    'csvHtml5',
                text:      '<i class="fa fa-file-text-o"></i> &nbsp; CSV',
                titleAttr: 'CSV',
                title: $('h3').text(),
                  exportOptions: {
        columns: [0,1, 2, 3,4,5], // Only name, email and role
    }
            },
            {
                extend:    'pdfHtml5',
                text:      '<i class="fa fa-file-pdf-o"></i>&nbsp;  PDF',
                
              customize: function (doc) {
						//Remove the title created by datatTables
						doc.content.splice(0,1);
						//Create a date string that we use in the footer. Format is dd-mm-yyyy
						var now = new Date();
						var jsDate = now.getDate()+'-'+(now.getMonth()+1)+'-'+now.getFullYear();
						
						doc.pageMargins = [20,60,20,20];
						doc.defaultStyle.fontSize = 10;
						doc.styles.tableHeader.fontSize = 10;
						doc['header']=(function() {
							return {
								columns: [{
									    alignment: 'left',
										image: logo,
										width: 50,margin: [200,5]
									},{
										alignment: 'CENTER',
										text: 'List of Client',
										fontSize: 20,
										margin: [10,35],
									},],
								margin: [20, 0, 0,12],alignment: 'center',
							}
						});
						var objLayout = {};
						objLayout['hLineWidth'] = function(i) { return 2; };
						objLayout['vLineWidth'] = function(i) { return 2; };
						objLayout['hLineColor'] = function(i) { return '#ccc'; };
						objLayout['vLineColor'] = function(i) { return '#ccc'; };
						objLayout['paddingLeft'] = function(i) { return 14; };
						objLayout['paddingRight'] = function(i) { return 14; };
						doc.content[0].layout = objLayout;
				},
				titleAttr: 'PDF',
                  exportOptions: {
        columns: [0,1, 2, 3,4,5], // Only name, email and role
    }
            },
            {
           extend: 'print',
          text: '<i class="fa fa-print"></i>&nbsp; Print',
          titleAttr: 'Print',
        customize: function ( win ) {
                    $(win.document.body)
                        .css( 'font-size', '10pt' )
                        .prepend(
                            '<center><img src=""/></center>'
                        );
                    $(win.document.body).find( 'table' )
                        .addClass( 'compact' )
                        .css( 'font-size', 'inherit' );
                },
         exportOptions: {
          columns: [0,1, 2, 3,4,5]
      },
      footer: true,
      autoPrint: true
    },],
    } );
$('input.global_filter').on( 'keyup click', function () {
        filterGlobal();
    } );
 
    $('input.column_filter').on( 'keyup click', function () {
        filterColumn( $(this).parents('tr').attr('data-column') );
    } );
  table.on( 'order.dt search.dt', function () {
       table.column(0, {search:'applied', order:'applied'}).nodes().each( function (cell, i) {
          cell.innerHTML = i + 1;
          table.cell(cell).invalidate('dom'); 
       } );
    } ).draw();
       table.columns(6)
        .search('^(?:(?!Inactive|New|1).)*$\r?\n?', true, false)
        .draw();
    $("#choice").on("change",function(){
 var _val = $(this).val();//alert(_val);
 
 if(_val == 'Inactive'){   
        table.columns(6).search(_val).draw();
  }
 else if(_val == 'New'){   
        table.columns(6).search(_val).draw();
  }
  else if(_val == 'Active'){  //alert();
         table.columns(6).search(_val).draw();
          table.columns(6)
        .search('^(?:(?!Inactive|New|1).)*$\r?\n?', true, false)
        .draw();
  }
  else{
        table
        .columns()
        .search('')
        .draw(); 
  }
  })
} );
   	</script>
@endsection()