routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!getJsonOfWork
|
*/
Route::get('/request-log', function()
{
    return view('/request-log');
});
Route::get('/clear-cache', function() {
    Artisan::call('cache:clear');
    return "Cache is cleared";
});

// Route::get('/makeController', function() {
//     Artisan::call('make:controller Test --resources');
//     return "Controller Created";
// });

Auth::routes();
 
Route::get('/request-login', 'submission\Auth\LoginController@showLoginForm')->name('requestlogin');

Route::post('submission/logout', 'submission\Auth\SubmissionLoginController@logout')->name('submission.logout');

Route::post('/request-login', 'submission\Auth\LoginController@requestlogin');
Route::resource('fscemployee/empclientreport','employee\EmpclientreportController');
Route::resource('fscemployee/empworkreport','employee\EmpworkreportController');

Route::resource('fscemployee/eereport','employee\EmpreportController');
Route::resource('fscemployee/eescheduleworkreport','employee\EmpschedulereportController');

Route::resource('fscemployee/employees','employee\EmployeesController');
Route::resource('fscemployee/workstatus','employee\WorkstatusController');

Route::resource('client/home', 'HomeController');
Route::resource('fscemployee/empsstates','employee\TaxStateEmpsController');
Route::resource('fscemployee/empstates','employee\TaxStateEmpController');
Route::resource('fscemployee/emptaxation','employee\TaxationEmpController');

Route::resource('fscemployee/appointment','employee\EmpAppointmentController');
Route::resource('fscemployee/eemail','employee\EmployeeEmailController');

Route::post('fscemployee/clients/addweges/{id}',['as'=>'clients.addweges','uses'=>'employee\EmploController@addweges']);
Route::post('fscemployee/clients/addwegesbanks/{id}',['as'=>'clients.addwegesbanks','uses'=>'employee\EmploController@addwegesbanks']);
Route::post('fscemployee/addnotesrelated1',['as'=>'addnotesrelated1','uses'=>'employee\EmploController@addnotesrelated1']);
Route::post('fscemployee/notesrelateds1',['as'=>'notesrelated1.notesrelateds1','uses'=>'employee\EmploController@notesrelateds1']);
Route::post('/utilitiess','employee\SchedulesController@utilitiess');
Route::get('/removeutilitiess','employee\SchedulesController@removeutilitiess');
Route::post('/otherbusinesss','employee\SchedulesController@otherbusinesss');  
Route::get('/removebusinesss','employee\SchedulesController@removebusinesss');
Route::post('/insurances','employee\SchedulesController@insurances');  
Route::get('/removeinsurances','employee\SchedulesController@removeinsurances');

Route::post('fscemployee/addcoversationsheet1',['as'=>'addcoversationsheet1','uses'=>'employee\EmploController@addcoversationsheet1']);
Route::post('fscemployee/tasks/search', 'employee\TasksController@search')->name('tasks.search');
Route::post('fac-Bhavesh-0554/purpose',['as'=>'purpose.purposes','uses'=>'Admin\MessageController@purposes']);
Route::get('client/getRequest2','HomeController@getcategory2');
Route::post('client/checkpassword','HomeController@getpassword');

Route::post('fac-Bhavesh-0554/addcoversationsheet',['as'=>'addcoversationsheet','uses'=>'AdminController@addcoversationsheet']);
Route::post('fac-Bhavesh-0554/addnotesrelated',['as'=>'addnotesrelated','uses'=>'AdminController@addnotesrelated']);
Route::post('fac-Bhavesh-0554/workrecord',['as'=>'workrecord.creates','uses'=>'Admin\WorkrecordController@creates']);
Route::post('fac-Bhavesh-0554/workrecord',['as'=>'workrecord.store','uses'=>'Admin\WorkrecordController@store']);

Route::get('client/getcat1','HomeController@getcategory111');
Route::get('client/getusers/{filename}','HomeController@getusers');

Route::get('applycounty','Front\ApplyservicessController@applycounty1');
Route::get('/getstateList','Front\ApplyEmploymentContoller@getStateList');
Route::resource('schedule1','Admin\ScheduleupController');

Route::get('propspectAccept/accept_proposal/','Admin\ProposalAcceptController@accept_proposal');
Route::resource('propspectAccept','Admin\ProposalAcceptController');

Route::get('/fetch-company', 'Admin\ScheduleController@schedules');
Route::resource('submission/dashboard','Front\RequestSubmissionController');
Route::resource('client/clientvendor','User\VendorssController');
Route::get('/fscgetschedule','employee\SchedulesController@fscemployee1');
Route::get('/fscgetduration','employee\SchedulesController@fscgetduration1');
Route::get('/getadminlic','Admin\AdminworkstatusController@getadminlic');
Route::get('/getadminformation','Admin\AdminworkstatusController@getadminformation');
Route::get('/getadminformation2','Admin\AdminworkstatusController@getadminformation2');

Route::post('/income','employee\SchedulesController@incomeadd');
Route::post('/emptax','employee\SchedulesController@emptaxadd');
Route::get('/getDependent','employee\SchedulesController@getDependent');
Route::post('/depend','employee\SchedulesController@dependentadd');
Route::get('/deletedepend/{id}','employee\SchedulesController@destroydependent');
Route::get('/deletefile/{id}','employee\SchedulesController@destroyfilling');
Route::get('/deleteexp/{id}','employee\SchedulesController@deleteexp');
Route::post('/expense','employee\SchedulesController@expenseadd');

Route::post('/updatedependent','employee\SchedulesController@updatedependent');
Route::get('/otherWeges','employee\SchedulesController@otherWeges');
Route::get('/getWeges','employee\SchedulesController@getWeges');
Route::get('/getExpense','employee\SchedulesController@getExpense');
Route::post('/updateincomeweges','employee\SchedulesController@updateincomeweges');
Route::post('/updateotherweges','employee\SchedulesController@updateotherweges');
Route::post('/updateexpense','employee\SchedulesController@updateexpense');
Route::get('/getTaxations','employee\SchedulesController@getTaxations');
Route::post('/updateintaxation','employee\SchedulesController@updateintaxation');

Route::get('removenotenote/removenotesnote1', ['as' => 'removenotenote.removenotesnote1', 'uses' => 'employee\EmploController@removenotenotes']);
Route::get('getComplete/getComplete1', ['as' => 'getComplete.getComplete1', 'uses' => 'employee\EmploController@getComplete']);

Route::post('/login1', 'Clients\Auth\EmployeeClientLoginController@login1'); 
Route::get('/login1', 'Clients\Auth\EmployeeClientLoginController@showLoginForm1')->name('login1');

Route::prefix('clientemployee')->group(function()
{
Route::post('/logout', 'Clients\Auth\EmployeeClientLoginController@logout')->name('clientemployee.logout'); 

Route::resource('home', 'Clients\ClientsController');
Route::resource('', 'Clients\ClientsController');

Route::resource('clientprofile','Clients\ClientprofileController');
Route::resource('clientchangepassword','Clients\ClientchangepasswordController');
Route::post('clientchangepass','Clients\ClientchangepasswordController@getpassword12');
Route::post('/super', 'Clients\ClientsController@supervisor_suepr');
Route::post('/super1', 'Clients\ClientsController@supervisor_suepr1');

Route::post('/superstart2', 'Clients\ClientsController@supervisor_sueprstart2');
Route::post('/superend2', 'Clients\ClientsController@supervisor_sueprend2');

Route::match(['get', 'post'], '/profilephoto1/{id}', 'Clients\ClientprofileController@profilephoto');  
Route::match(['get', 'post'], '/additional/{id}', 'Clients\ClientprofileController@additional1');
Route::match(['get', 'post'], '/additional2/{id}', 'Clients\ClientprofileController@additional2');
Route::match(['get', 'post'], '/additional3/{id}', 'Clients\ClientprofileController@additional3');
Route::match(['get', 'post'], '/pfidd/{id}', 'Clients\ClientprofileController@pfidd');
Route::match(['get', 'post'], '/pfidd1/{id}', 'Clients\ClientprofileController@pfidd1');
});

Route::group(['namespace'=>'Front'],function()
{ 
Route::resource('/', 'FrontController');    
Route::get('register-user','RegisterController@index');
Route::get('getFormation','FormationController@getFormation');

Route::resource('user/client','UsercronController'); 
Route::get('business-registration/{busid}/{type}','CategoryController@index');
Route::get('brand-nonbrand/{busid}/{bustype}/{catid}','BrandNonbrandController@index');
Route::get('non-profit-organization-registration/{id}','NonprofitController@index');
Route::get('business-brand-category-list/{brandid}/{catid}/{busid}/{type}','BusinessbrandcategoryController@index');

Route::resource('comman-registration','CommonRegistrationController');
Route::post('/checkclient','CommonRegistrationController@checkclientAvailability');
Route::post('/checkclient11','CommonRegistrationController@checkclientAvailability11');
Route::post('/checkclientids','CommonRegistrationController@checkclientcheckclientids');
Route::post('/clientname1','CommonRegistrationController@clientname');
Route::get('/getfilename','CommonRegistrationController@getfilename');
Route::get('comman-registration/create/{catid}/{bustype}/{busid}/{brandid}/{brandcatid}','CommonRegistrationController@create');
Route::get('comman-registration/create/{catid}/{bustype}/{busid}/{brandid}','CommonRegistrationController@create');
Route::get('comman-registration/create/{busid}/{bustype}/{catid}','CommonRegistrationController@create');
Route::get('comman-registration/create/{busid}/{bustype}','CommonRegistrationController@create');

Route::get('service-industry-registration/{busid}/{type}','ServiceindustryregistrationController@index');
Route::get('professions-registration/{busid}/{type}','ProfessionsController@index');
Route::get('investor-registration/{busid}/{type}','investorController@index');

resources/views/clientemployee/empsstates/create.blade.php
@extends('clientemployee.layouts.app')
@section('main-content')
<div class="content-wrapper">
      <!-- Content Header (Page header) -->
    <section class="page-title content-header">
     		<h1>County</h1>
    </section>
    <!-- Main content -->
    <section class="content">
   <div class="row">
      <div class="col-md-12">
        	<div class="box box-success">
			      <div class="box-header">
             
              <div class="box-tools pull-right">
                
              </div>
            </div>
				<div class="col-md-12">
               <form method="post" action="{{route('empsstates.store')}}" class="form-horizontal" id="businessname" name="businessname" enctype="multipart/form-data">
                  {{csrf_field()}}
                  <div class="form-group {{ $errors->has('state') ? ' has-error' : '' }}">
                     <label class="control-label col-md-3">State :</label>
                     <div class="col-md-4">
                        <select name="state" id="state" class="form-control fsc-input">
                                                            <option value="">---Select State---</option>                                          
                                                                                                      <option value="AK">AK</option>
                                                   <option value="AS">AS</option>
                                                   <option value="AZ">AZ</option>
                                                   <option value="AR">AR</option>
                                                   <option value="CA">CA</option>
                                                   <option value="CO">CO</option>
                                                   <option value="CT">CT</option>
                                                   <option value="DE">DE</option>
                                                   <option value="DC">DC</option>
                                                   <option value="FM">FM</option>
                                                   <option value="FL">FL</option>
                                                   <option value="GA">GA</option>
                                                   <option value="GU">GU</option>
                                                   <option value="HI">HI</option>
                                                   <option value="ID">ID</option>
                                                   <option value="IL">IL</option>
                                                   <option value="IN">IN</option>
                                                   <option value="IA">IA</option>
                                                   <option value="KS">KS</option>
                                                   <option value="KY">KY</option>
                                                   <option value="LA">LA</option>
                                                   <option value="ME">ME</option>
                                                   <option value="MH">MH</option>
                                                   <option value="MD">MD</option>
                                                   <option value="MA">MA</option>
                                                   <option value="MI">MI</option>
                                                   <option value="MN">MN</option>
                                                   <option value="MS">MS</option>
                                                   <option value="MO">MO</option>
                                                   <option value="MT">MT</option>
                                                   <option value="NE">NE</option>
                                                   <option value="NV">NV</option>
                                                   <option value="NH">NH</option>
                                                   <option value="NJ">NJ</option>
                                                   <option value="NM">NM</option>
                                                   <option value="NY">NY</option>
                                                   <option value="NC">NC</option>
                                                   <option value="ND">ND</option>
                                                   <option value="MP">MP</option>
                                                   <option value="OH">OH</option>
                                                   <option value="OK">OK</option>
                                                   <option value="OR">OR</option>
                                                   <option value="PW">PW</option>
                                                   <option value="PA">PA</option>
                                                   <option value="PR">PR</option>
                                                   <option value="RI">RI</option>
                                                   <option value="SC">SC</option>
                                                   <option value="SD">SD</option>
                                                   <option value="TN">TN</option>
                                                   <option value="TX">TX</option>
                                                   <option value="UT">UT</option>
                                                   <option value="VT">VT</option>
                                                   <option value="VI">VI</option>
                                                   <option value="VA">VA</option>
                                                   <option value="WA">WA</option>
                                                   <option value="WV">WV</option>
                                                   <option value="WI">WI</option>
                                                   <option value="WY">WY</option>
                                                </select>
                        @if ($errors->has('state'))
                        <span class="help-block">
                        <strong>{{ $errors->first('state') }}</strong>
                        </span>
                        @endif
                     </div>
                  </div>
                  <div class="form-group {{ $errors->has('county') ? ' has-error' : '' }}">
                     <label class="control-label col-md-3">County Name :</label>
                     <div class="col-md-4">
                        <input type="text" name="county" id=county" class="form-control"  placeholder="County Name" /> 
                        @if ($errors->has('county'))
                        <span class="help-block">
                        <strong>{{ $errors->first('county') }}</strong>
                        </span>
                        @endif
                     </div>
                  </div>
                  <div class="form-group {{ $errors->has('countycode') ? ' has-error' : '' }}">
                     <label class="control-label col-md-3">County Code :</label>
                     <div class="col-md-4">
                        <input type="text" name="countycode" id="countycode" class="form-control "  placeholder="County Code" /> 
                        @if ($errors->has('countycode'))
                        <span class="help-block">
                        <strong>{{ $errors->first('countycode') }}</strong>
                        </span>
                        @endif
                     </div>
                  </div>
	          <div class="form-group {{ $errors->has('type') ? ' has-error' : '' }}">
                     <label class="control-label col-md-3">Type :</label>
                     <div class="col-md-4">
                        <input type="text" name="type" id="type" readonly value="County" class="form-control num"  placeholder="Type" /> 
                        @if ($errors->has('type'))
                        <span class="help-block">
                        <strong>{{ $errors->first('type') }}</strong>
                        </span>
                        @endif
                     </div>
                  </div>
	          <div class="form-group {{ $errors->has('rate') ? ' has-error' : '' }}">
                     <label class="control-label col-md-3">Rate :</label>
                     <div class="col-md-4">
                        <input type="text" name="rate" id="rate" class="form-control "  placeholder="Rate" /> 
                        @if ($errors->has('rate'))
                        <span class="help-block">
                        <strong>{{ $errors->first('rate') }}</strong>
                        </span>
                        @endif
                     </div>
                  </div>
	         
                  <div class="card-footer">
                    <div class="col-md-2 col-md-offset-3">
									<input class="btn_new_save btn-primary1" style="margin-left:-5%" type="submit" name="submit" value="Save">
									</div>
									<div class="col-md-2 row">
									<a class="btn_new_cancel" href="{{url('fscemployee/empsstates')}}">Cancel</a> 
									</div>
                  </div>
               
            </div>
            </form>
         </div>
      </div>
   </div>
</div>
</section>
</div>
@endsection()

resources/views/clientemployee/empsstates/edit.blade.php
@extends('clientemployee.layouts.app')
@section('main-content')
<div class="content-wrapper">
      <!-- Content Header (Page header) -->
    <section class="page-title content-header">
     		<h1>County</h1>
    </section>
    <!-- Main content -->
    <section class="content">
   <div class="row">
      <div class="col-md-12">
         	<div class="box box-success">
			      <div class="box-header">
              <div class="box-tools pull-right"></div>
            </div>
				<div class="col-md-12">
                      <div class="Branch">
                                       <h1>Federal</h1>
                                    </div><br>
               <form method="post" action="{{route('empsstates.update',$state->id)}}" class="form-horizontal" id="businessname" name="businessname" enctype="multipart/form-data">
                  {{csrf_field()}}{{method_field('PATCH')}}
                 <div class="form-group {{ $errors->has('state') ? ' has-error' : '' }}">
                     <label class="control-label col-md-3">State :</label>
                     <div class="col-md-4">
                        <select name="state" id="state" class="form-control fsc-input">
                                @if($state->state)
                                    <option value="{{$state->state}}">{{$state->state}}</option>
                                @else
                                    <option value="">---Select State---</option>
                                @endif                                          
                                                   <option value="AK">AK</option>
                                                   <option value="AS">AS</option>
                                                   <option value="AZ">AZ</option>
                                                   <option value="AR">AR</option>
                                                   <option value="CA">CA</option>
                                                   <option value="CO">CO</option>
                                                   <option value="CT">CT</option>
                                                   <option value="DE">DE</option>
                                                   <option value="DC">DC</option>
                                                   <option value="FM">FM</option>
                                                   <option value="FL">FL</option>
                                                   <option value="GA">GA</option>
                                                   <option value="GU">GU</option>
                                                   <option value="HI">HI</option>
                                                   <option value="ID">ID</option>
                                                   <option value="IL">IL</option>
                                                   <option value="IN">IN</option>
                                                   <option value="IA">IA</option>
                                                   <option value="KS">KS</option>
                                                   <option value="KY">KY</option>
                                                   <option value="LA">LA</option>
                                                   <option value="ME">ME</option>
                                                   <option value="MH">MH</option>
                                                   <option value="MD">MD</option>
                                                   <option value="MA">MA</option>
                                                   <option value="MI">MI</option>
                                                   <option value="MN">MN</option>
                                                   <option value="MS">MS</option>
                                                   <option value="MO">MO</option>
                                                   <option value="MT">MT</option>
                                                   <option value="NE">NE</option>
                                                   <option value="NV">NV</option>
                                                   <option value="NH">NH</option>
                                                   <option value="NJ">NJ</option>
                                                   <option value="NM">NM</option>
                                                   <option value="NY">NY</option>
                                                   <option value="NC">NC</option>
                                                   <option value="ND">ND</option>
                                                   <option value="MP">MP</option>
                                                   <option value="OH">OH</option>
                                                   <option value="OK">OK</option>
                                                   <option value="OR">OR</option>
                                                   <option value="PW">PW</option>
                                                   <option value="PA">PA</option>
                                                   <option value="PR">PR</option>
                                                   <option value="RI">RI</option>
                                                   <option value="SC">SC</option>
                                                   <option value="SD">SD</option>
                                                   <option value="TN">TN</option>
                                                   <option value="TX">TX</option>
                                                   <option value="UT">UT</option>
                                                   <option value="VT">VT</option>
                                                   <option value="VI">VI</option>
                                                   <option value="VA">VA</option>
                                                   <option value="WA">WA</option>
                                                   <option value="WV">WV</option>
                                                   <option value="WI">WI</option>
                                                   <option value="WY">WY</option>
                                                </select>
                        @if ($errors->has('state'))
                        <span class="help-block">
                        <strong>{{ $errors->first('state') }}</strong>
                        </span>
                        @endif
                     </div>
                  </div>
                  <div class="form-group {{ $errors->has('county') ? ' has-error' : '' }}">
                     <label class="control-label col-md-3">County Name :</label>
                     <div class="col-md-4">
                        <input type="text" name="county" id=county" class="form-control" value="{{$state->county}}" placeholder="County Name" /> 
                        @if ($errors->has('county'))
                        <span class="help-block">
                        <strong>{{ $errors->first('county') }}</strong>
                        </span>
                        @endif
                     </div>
                  </div>
                  <div class="form-group {{ $errors->has('countycode') ? ' has-error' : '' }}">
                     <label class="control-label col-md-3">County Code :</label>
                     <div class="col-md-4">
                        <input type="text" name="countycode" id="countycode" class="form-control" value="{{$state->countycode}}"  placeholder="County Code" /> 
                        @if ($errors->has('countycode'))
                        <span class="help-block">
                        <strong>{{ $errors->first('countycode') }}</strong>
                        </span>
                        @endif
                     </div>
                  </div>
	          <div class="form-group {{ $errors->has('type') ? ' has-error' : '' }}">
                     <label class="control-label col-md-3">Type :</label>
                     <div class="col-md-4">
                        <input type="text" name="type" id="type" class="form-control num"  value="{{$state->type}}" placeholder="Type" /> 
                        @if ($errors->has('type'))
                        <span class="help-block">
                        <strong>{{ $errors->first('type') }}</strong>
                        </span>
                        @endif
                     </div>
                  </div>
	          <div class="form-group {{ $errors->has('rate') ? ' has-error' : '' }}">
                     <label class="control-label col-md-3">Rate :</label>
                     <div class="col-md-4">
                        <input type="text" name="rate" id="rate" class="form-control"  value="{{$state->rate}}"  placeholder="Rate" /> 
                        @if ($errors->has('rate'))
                        <span class="help-block">
                        <strong>{{ $errors->first('rate') }}</strong>
                        </span>
                        @endif
                     </div>
                  </div>
	         <div class="card-footer">
                   <div class="col-md-2 col-md-offset-3">
								<!--	<input class="btn_new_save btn-primary1" style="margin-left:-5%" type="submit" name="submit" value="Save">-->
									</div>
									<div class="col-md-2 row">
									<a class="btn_new_cancel" href="{{url('fscemployee/empsstates')}}">Cancel</a> 
									</div>
                  </div>
               </form>
            </div>
         </div>
      </div>
   </div>
     </section>
</div>


@endsection()

resources/views/clientemployee/empsstates/empsstates.blade.php
@extends('clientemployee.layouts.app')
@section('main-content')
<div class="content-wrapper">
	   <!-- Content Header (Page header) -->
    <section class="content-header page-title" style="height:50px;">
     		<div class="row col-md-12">
     		    <div class="col-md-7" style="text-align:right;">
     		        <h1>List of County</h1>
     		    </div>
     		    <div class="col-md-5" style="text-align:right;">
     		        <h1>Add / View / Edit</h1>
     		    </div>
     		</div>
    </section>
    <section class="content">
	<div class="row">
		<div class="col-md-12">
				<div class="box box-success">
			      <div class="box-header">
              <div class="box-tools pull-right">
                <div class="table-title">
					</div>
              </div>
            </div>
				<div class="col-md-12">
					<div class="table-responsive">
						<table class="table table-hover table-bordered" id="sampleTable3">
							<thead>
								<tr>
									<th>No</th>
									<th>State</th>
									<th>County</th>
                 					<th>County Code</th>
									<th>Action</th>
								</tr>
							</thead>
							<tbody>
                                @foreach($price as $bus)
								<tr>
									<td style="text-align:center;">{{$loop->index + 1}}</td>
									<td style="text-align:center;">{{$bus->state}}</td>
									<td style="text-align:center;">{{$bus->county}}</td>	
                                    <td style="text-align:center;">{{$bus->countycode}}</td>	
	                                <td style="text-align:center;"><a class="btn-action btn-view-edit" href="{{route('empsstates.edit', $bus->id)}}"><i class="fa fa-edit"></i></a>
                                    <form action="{{ route('empsstates.destroy',$bus->id) }}" method="post" style="display:none" id="delete-id-{{$bus->id}}">{{csrf_field()}} {{method_field('DELETE')}}</form> <a class="btn-action btn-delete" onclick="if(confirm('Are you sure, You want to delete this record ?')){event.preventDefault();document.getElementById('delete-id-{{$bus->id}}').submit();} else{event.preventDefault();}" href=""><i class="fa fa-trash"></i></a></td>
								</tr>
								@endforeach
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
		  </section>
</div>
@endsection()