routes/web.php
Route::get('adminworkstatus/newbankingdelete/{id}', ['as' => 'adminworkstatus.newbankingdelete', 'uses' => 'AdminworkstatusController@newbankingdelete']);
Route::get('workrecord/destroyfederal/{id}',['as'=>'workrecord.destroyfederal','uses'=>'WorkrecordController@destroyfederal']);
Route::get('workrecord/destroystate/{id}',['as'=>'workrecord.destroystate','uses'=>'WorkrecordController@destroystate']);
Route::get('clientsetup/destroyfilling/{id}',['as'=>'clientsetup.destroyfilling','uses'=>'ClientsetupController@destroyfilling']);
Route::get('clientsetup/destroydependent/{id}',['as'=>'clientsetup.destroydependent','uses'=>'ClientsetupController@destroydependent']);
Route::get('clientsetup/destroyincome/{id}',['as'=>'clientsetup.destroyincome','uses'=>'ClientsetupController@destroyincome']);
Route::get('clientsetup/destroyemployee/{empid}',['as'=>'clientsetup.destroyemployee','uses'=>'ClientsetupController@destroyemployee']);
Route::get('clientsetup/clients/destryotherincome/{id2}',['as'=>'clientsetup.destryotherincome','uses'=>'ClientsetupController@destryotherincome']);
Route::post('clientsetup/addweges/{id}',['as'=>'clientsetup.addweges','uses'=>'ClientsetupController@addweges']);
Route::post('clientsetup/addwegesbank/{id}',['as'=>'clientsetup.addwegesbank','uses'=>'ClientsetupController@addwegesbank']);
Route::post('clientsetup/updatedependent',['as'=>'clientsetup.updatedependent','uses'=>'ClientsetupController@updatedependent']);
Route::post('clientsetup/updateincomeweges',['as'=>'clientsetup.updateincomeweges','uses'=>'ClientsetupController@updateincomeweges']);
Route::post('clientsetup/updateotherweges',['as'=>'clientsetup.updateotherweges','uses'=>'ClientsetupController@updateotherweges']);
Route::post('clientsetup/updateexpense',['as'=>'clientsetup.updateexpense','uses'=>'ClientsetupController@updateexpense']);
Route::post('clientsetup/updateintaxation',['as'=>'clientsetup.updateintaxation','uses'=>'ClientsetupController@updateintaxation']);
Route::post('clientsetup/addutilitiesdetail',['as'=>'clientsetup.addutilitiesdetail','uses'=>'ClientsetupController@addutilitiesdetail']);

Route::get('clientsetup/destroyexp/{id}',['as'=>'clientsetup.destroyexp','uses'=>'ClientsetupController@destroyexp']);
Route::get('fscemployee/clients/destroyemployee/{empid}',['as'=>'clients.destroyemployee','uses'=>'employee\ClientsController@destroyemployee']);
Route::get('fscemployee/clients/destryotherincome/{id2}',['as'=>'clients.destryotherincome','uses'=>'employee\ClientsController@destryotherincome']);


Route::get('adminworkstatus/destroyprolic/{id}', ['as' => 'adminworkstatus.destroyprolic', 'uses' => 'AdminworkstatusController@destroyprolic']);
Route::get('adminworkstatus/destroydocument/{id}', ['as' => 'adminworkstatus.destroydocument', 'uses' => 'AdminworkstatusController@destroydocument']);
Route::get('adminworkstatus/destroydocumenttitle/{id}', ['as' => 'adminworkstatus.destroydocumenttitle', 'uses' => 'AdminworkstatusController@destroydocumenttitle']);


Route::get('fac-Bhavesh-0554/workrecord/destroydocumenttitle/{id}',['as'=>'workrecord.destroydocumenttitle','uses'=>'WorkrecordController@destroydocumenttitle']);
Route::get('fac-Bhavesh-0554/workrecord/destroydocument/{id}', ['as' => 'workrecord.destroydocument', 'uses' => 'WorkrecordController@destroydocument']);

Route::get('fscemployee/workrecord/destroydocumenttitle/{id}',['as'=>'workrecord.destroydocumenttitle','uses'=>'WorkrecordController@destroydocumenttitle']);

Route::get('clientsetup/getincomeweges/{id}/{cid}/{cids}', 'Admin\ClientsetupController@getincomeweges')->name('worknew.getincomeweges');


Route::resource('fac-Bhavesh-0554/taxcity','TaxCityController');
Route::resource('fac-Bhavesh-0554/empleave','EmpLeaveController');
Route::resource('fac-Bhavesh-0554/clientsetup','ClientsetupController');
Route::get('/getimagess','ClientsetupController@getimagesssss');
Route::get('/getcertificate','ClientsetupController@getcertificate');
Route::get('/getAdmincertificate','AdminProfileController@getAdmincertificate');

Route::get('/getAdminprolic','AdminProfileController@getAdminprolic');

Route::get('/getaoi','ClientsetupController@getaoi');
Route::get('/getAdminaoi','AdminProfileController@getAdminaoi');
Route::get('/getWorkannual','ClientsetupController@getWorkannual');
Route::get('/getWorkofficer','ClientsetupController@getWorkofficer');



Route::post('adminworkstatus','AdminworkstatusController@store'); 


Route::get('/client_number','ClientsetupController@client_number1');
Route::resource('fac-Bhavesh-0554/cservice','CSServiceController');

Route::resource('fac-Bhavesh-0554/adminupload','AdminUploadController');
Route::resource('fac-Bhavesh-0554/clientupload','ClientUploadController');
Route::resource('fac-Bhavesh-0554/contactinquery','ContactinqueryController');
Route::resource('fac-Bhavesh-0554/linkinquery','LinkinqueryController');
Route::resource('fac-Bhavesh-0554/control','ControlController');
Route::resource('fac-Bhavesh-0554/marque','MarqueController');
Route::resource('fac-Bhavesh-0554/zipcode','ZipcodeController');
Route::resource('fac-Bhavesh-0554/citystate','CitystateController');

Route::resource('fac-Bhavesh-0554/categorys','CategorysController');
Route::resource('fac-Bhavesh-0554/subcategorys','SubcategorysController');
Route::resource('fac-Bhavesh-0554/questionsection','QuestionSectionController');

Route::get('fac-Bhavesh-0554/addressbook','AddressbookController@index');
Route::get('fac-Bhavesh-0554/addressbook/{id}/{type}/edit',['as'=>'addressbook.edit','uses'=>'AddressbookController@edit']); 
Route::resource('fac-Bhavesh-0554/question','QuestionController');
Route::resource('fac-Bhavesh-0554/formationsetup','FormationSetupController');

Route::resource('fac-Bhavesh-0554/license','LicenseController');

Route::resource('fac-Bhavesh-0554/taxation','TaxationSetupController');
Route::get('states/destroylicense/{id}', ['as' => 'states.destroylicense', 'uses' => 'TaxStatesController@destroylicense']);

Route::get('fac-Bhavesh-0554/answer/create/{id}','AnswerController@create');

Route::resource('fac-Bhavesh-0554/answer', 'AnswerController', ['only' => ['store']]);

Route::resource('fac-Bhavesh-0554/rules','RulesController');
Route::get('clientd/clientdelete/{id}', ['as' => 'clientd.clientdelete', 'uses' => 'ClientsetupController@clientdelete']);

Route::get('admind2/admindelete2/{id}/{ccid}', ['as' => 'admind2.admindelete2', 'uses' => 'ClientsetupController@clientdelete1']);


Route::get('review/reviewdelete/{id}', ['as' => 'review.reviewdelete', 'uses' => 'EmployeeController@reviewdelete1']);
Route::get('employee/removeimage/{id}', ['as' => 'employee.removeimage', 'uses' => 'EmployeeController@removeimage']);
Route::get('employee/removeemailrights/{id}/{empid}', ['as' => 'employee.removeemailrights', 'uses' => 'EmployeeController@removeEmailRights']);
Route::get('employee/removeimage1/{id}', ['as' => 'employee.removeimage1', 'uses' => 'EmployeeController@removeimage1']);
Route::get('employee/removeimage2/{id}', ['as' => 'employee.removeimage2', 'uses' => 'EmployeeController@removeimage2']);
Route::get('employee/removeimage3/{id}', ['as' => 'employee.removeimage3', 'uses' => 'EmployeeController@removeimage3']);



Route::get('pay/paydelete/{id}', ['as' => 'pay.paydelete', 'uses' => 'EmployeeController@paydelete1']);
Route::get('admind1/admindelete1/{id}', ['as' => 'admind1.admindelete1', 'uses' => 'AdminProfileController@admindelete1']);
Route::get('admin/adminbankdelete/{id}', ['as' => 'admin.adminbankdelete', 'uses' => 'AdminProfileController@adminbankdelete']);
Route::get('admin/admincarddelete/{id}', ['as' => 'admin.admincarddelete', 'uses' => 'AdminProfileController@admincarddelete']);

Route::get('admin/clientbankdatadelete/{id}', ['as' => 'admin.clientbankdatadelete', 'uses' => 'ClientsetupController@clientbankdatadelete']);
Route::get('admin/clientcarddatadelete/{id}', ['as' => 'admin.clientcarddatadelete', 'uses' => 'ClientsetupController@clientcarddatadelete']);
Route::resource('fac-Bhavesh-0554/emptechnical','EmptechnicalController');

Route::get('admind/admindelete/{id}', ['as' => 'admind.admindelete', 'uses' => 'AdminProfileController@admindelete']);
Route::get('note/notedelete/{id}', ['as' => 'note.notedelete', 'uses' => 'AdminProfileController@notedelete']);

Route::post('fac-Bhavesh-0554/adminprofile/updateformation',['as'=>'adminprofile.updateformation','uses'=>'AdminProfileController@updateformation']);

Route::get('empnote/empnotedelete/{id}', ['as' => 'empnote.empnotedelete', 'uses' => 'EmployeeController@empnotedelete']);
Route::get('taxa/taxadelete/{id}', ['as' => 'taxa.taxadelete', 'uses' => 'PriceController@taxadelete1']);
Route::get('emppay/emppaydelete/{id}', ['as' => 'emppay.emppaydelete', 'uses' => 'EmployeeController@emppaydelete']);
Route::get('empwh/empwhdelete/{id}', ['as' => 'empwh.empwhdelete', 'uses' => 'EmployeeController@empwhdelete']);

Route::get('empreview/empreviewdelete/{id}', ['as' => 'empreview.empreviewdelete', 'uses' => 'EmployeeController@empreviewdelete']);


Route::get('contactinfo/contactdelete/{id}', ['as' => 'contactinfo.contactdelete', 'uses' => 'EmployeeController@contactdelete']);

Route::resource('fac-Bhavesh-0554/servicesprocess','ServiceinquiryController');

Route::resource('fac-Bhavesh-0554/appointment','AppointmentController');
Route::post('/events','CalenderController@event');
Route::resource('fac-Bhavesh-0554/clienttechnical','ClienttechnicalController');
Route::resource('fac-Bhavesh-0554/calender','CalenderController');
Route::resource('fac-Bhavesh-0554/email','EmailController');
Route::resource('fac-Bhavesh-0554/getemail','GetemailController');
Route::get('/cestatus1','CestatusController@cestatus');
Route::get('/getdata','CestatusController@getdata1');
Route::resource('fac-Bhavesh-0554/cestatus','CestatusController');
Route::resource('fac-Bhavesh-0554/insurance','InsController');
Route::resource('fac-Bhavesh-0554/supervisor','SupervisorController');

resources/views/fac-Bhavesh-0554/servicesprocess/create.blade.php
@extends('fac-Bhavesh-0554.layouts.app')
@section('main-content')
<div class="content-wrapper">
   <div class="page-title">
      <h1>Employment</h1>
   </div>
   <div class="row">
      <div class="col-md-12">
         <div class="card">
            <div class="card-body">
               <form method="post" action="{{route('employment.store')}}" class="form-horizontal" id="content" name="content" enctype="multipart/form-data">
                  {{csrf_field()}}
                  <div class="form-group{{ $errors->has('position_name') ? ' has-error' : '' }}">
                     <label class="control-label col-md-3">Position Name :</label>
                     <div class="col-md-8">
                        <input name="position_name" type="text" id="position_name" class="form-control" value="" />	
                        @if ($errors->has('position_name'))
                        <span class="help-block">
                        <strong>{{ $errors->first('position_name') }}</strong>
                        </span>
                        @endif							
                     </div>
                  </div>
                  <div class="form-group{{ $errors->has('country') ? ' has-error' : '' }}">
                     <label class="control-label col-md-3">Country:</label>
                     <div class="col-md-8">
                        <div class="box-body pad">
                           <select name="country" id="country" class="form-control fsc-input">
                              <option value="">---Select Country---</option>
                              <option value='USA'>USA</option>
                           </select>
                        </div>
                        @if ($errors->has('country'))
                        <span class="help-block">
                        <strong>{{ $errors->first('country') }}</strong>
                        </span>
                        @endif	
                     </div>
                  </div>
                  <div class="form-group{{ $errors->has('state') ? ' has-error' : '' }}">
                     <label class="control-label col-md-3">State :</label>
                     <div class="col-md-8">
                        <div class="box-body pad">
                           <select name="state" id="state" class="form-control fsc-input">
                              <option value="">---Select State---</option>
                              <option value='AK'>AK</option>
                              <option value='AS'>AS</option>
                              <option value='AZ'>AZ</option>
                              <option value='AR'>AR</option>
                              <option value='CA'>CA</option>
                              <option value='CO'>CO</option>
                              <option value='CT'>CT</option>
                              <option value='DE'>DE</option>
                              <option value='DC'>DC</option>
                              <option value='FM'>FM</option>
                              <option value='FL'>FL</option>
                              <option value='GA'>GA</option>
                              <option value='GU'>GU</option>
                              <option value='HI'>HI</option>
                              <option value='ID'>ID</option>
                              <option value='IL'>IL</option>
                              <option value='IN'>IN</option>
                              <option value='IA'>IA</option>
                              <option value='KS'>KS</option>
                              <option value='KY'>KY</option>
                              <option value='LA'>LA</option>
                              <option value='ME'>ME</option>
                              <option value='MH'>MH</option>
                              <option value='MD'>MD</option>
                              <option value='MA'>MA</option>
                              <option value='MI'>MI</option>
                              <option value='MN'>MN</option>
                              <option value='MS'>MS</option>
                              <option value='MO'>MO</option>
                              <option value='MT'>MT</option>
                              <option value='NE'>NE</option>
                              <option value='NV'>NV</option>
                              <option value='NH'>NH</option>
                              <option value='NJ'>NJ</option>
                              <option value='NM'>NM</option>
                              <option value='NY'>NY</option>
                              <option value='NC'>NC</option>
                              <option value='ND'>ND</option>
                              <option value='MP'>MP</option>
                              <option value='OH'>OH</option>
                              <option value='OK'>OK</option>
                              <option value='OR'>OR</option>
                              <option value='PW'>PW</option>
                              <option value='PA'>PA</option>
                              <option value='PR'>PR</option>
                              <option value='RI'>RI</option>
                              <option value='SC'>SC</option>
                              <option value='SD'>SD</option>
                              <option value='TN'>TN</option>
                              <option value='TX'>TX</option>
                              <option value='UT'>UT</option>
                              <option value='VT'>VT</option>
                              <option value='VI'>VI</option>
                              <option value='VA'>VA</option>
                              <option value='WA'>WA</option>
                              <option value='WV'>WV</option>
                              <option value='WI'>WI</option>
                              <option value='WY'>WY</option>
                           </select>
                        </div>
                        @if ($errors->has('state'))
                        <span class="help-block">
                        <strong>{{ $errors->first('state') }}</strong>
                        </span>
                        @endif	
                     </div>
                  </div>
                  <div class="form-group{{ $errors->has('city') ? ' has-error' : '' }}">
                     <label class="control-label col-md-3">City :</label>
                     <div class="col-md-8">
                        <div class="box-body pad">
                           <input name="city" type="text" id="city" class="form-control txtOnly"> 
                        </div>
                        @if ($errors->has('city'))
                        <span class="help-block">
                        <strong>{{ $errors->first('city') }}</strong>
                        </span>
                        @endif	
                     </div>
                  </div>
                  <div class="form-group{{ $errors->has('description') ? ' has-error' : '' }}">
                     <label class="control-label col-md-3">Description :</label>
                     <div class="col-md-8">
                        <div class="box-body pad">
                           <textarea id="editor1" name="description" rows="10" cols="80"></textarea>
                        </div>
                        @if ($errors->has('description'))
                        <span class="help-block">
                        <strong>{{ $errors->first('description') }}</strong>
                        </span>
                        @endif	
                     </div>
                  </div>
                  <div class="form-group{{ $errors->has('date') ? ' has-error' : '' }}">
                     <label class="control-label col-md-3">Date :</label>
                     <div class="col-md-8">
                        <div class="box-body pad">
                           <input name="date" type="text" id="date" class="form-control" readonly="readonly"> 
                        </div>
                        @if ($errors->has('date'))
                        <span class="help-block">
                        <strong>{{ $errors->first('date') }}</strong>
                        </span>
                        @endif	
                     </div>
                  </div>
                  <div class="form-group{{ $errors->has('type') ? ' has-error' : '' }}">
                     <label class="control-label col-md-3">Job Type :</label>
                     <div class="col-md-8">
                        <div class="box-body pad">
                           <select name="type" id="type" class="form-control fsc-input">
                              <option value="">---Select Post Type---</option>
                              <option value='Full Time'>Full Time</option>
                              <option value='Part Time'>Part Time</option>
                           </select>
                        </div>
                        @if ($errors->has('type'))
                        <span class="help-block">
                        <strong>{{ $errors->first('type') }}</strong>
                        </span>
                        @endif	
                     </div>
                  </div>
                  <div class="form-group{{ $errors->has('link') ? ' has-error' : '' }}">
                     <!--<label class="control-label col-md-3">Job Url :</label>-->
                     <div class="col-md-8">
                        <div class="box-body pad">
                           <input name="link" type="hidden" id="link" class="form-control" value="http://financialservicecenter.net/admin/employment/create"> 
                        </div>
                        @if ($errors->has('link'))
                        <span class="help-block">
                        <strong>{{ $errors->first('link') }}</strong>
                        </span>
                        @endif	
                     </div>
                  </div>
                  <div class="card-footer">
                     <div class="row">
                        <div class="col-md-8 col-md-offset-3">
                           <input class="btn btn-primary icon-btn upload-image" type="submit" name="submit" value="save">
                        </div>
                     </div>
                  </div>
               </form>
            </div>
         </div>
      </div>
   </div>
</div>
<script>
   CKEDITOR.replace('editor1');
</script>
<script>
   $(document).ready(function() {
  var dateInput = $('input[name="date"]'); // Our date input has the name "date"
  var container = $('.bootstrap-iso form').length > 0 ? $('.bootstrap-iso form').parent() : 'body';
  dateInput.datepicker({
    format: 'M/dd/yyyy',
    container: container,
    todayHighlight: true,
    autoclose: true,
    startDate: truncateDate(new Date()) // <-- THIS WORKS
  });

  $('#date').datepicker('setStartDate', truncateDate(new Date())); // <-- SO DOES THIS
});

function truncateDate(date) {
  return new Date(date.getFullYear(), date.getMonth(), date.getDate());
}
</script>
@endsection()

resources/views/fac-Bhavesh-0554/servicesprocess/servicesprocess.blade.php
@extends('fac-Bhavesh-0554.layouts.app')
@section('main-content')
<style>
label{float:left;}
.page-title{
        padding: 8px 15px;

}
</style>
<style>
    .buttons-pdf {
    font-size: 0px !important;
    border-radius: 3px;
    padding: 8px 10px !important;
    background: #fff !important;
    border-color: #c6c6c6  !important;
    color:red !important;
}
.buttons-print {
    font-size: 0px !important;
    border-radius: 3px;
    padding: 8px 10px !important;
    background: #3c8dbc !important;
            border-color: #367fa9 !important;
}
.buttons-excel{
    font-size:0px !important;
    border-radius: 3px;
        padding: 8px 10px !important;
        
         background: #00a65a !important;
    border-color: #008d4c !important;
        

}
.buttons-excel:hover{
     background: #008d4c !important;

}
.buttons-pdf:hover{
     background: #f6f6f6  !important;
}

.buttons-print:hover{
     background: #367fa9 !important;
}


.fa{
    font-size: 16px !important;
}
</style>
<div class="content-wrapper">
	   <!-- Content Header (Page header) -->
    
     <section class="content-header page-title" >
     		    <div>
     		        <h2>List of <?php if(isset($_REQUEST['typeofcorp']) && $_REQUEST['typeofcorp'] !='') { echo $_REQUEST['typeofcorp'];}?> -- Apply <span style="text-align:right;padding-right: 20px !important;position: absolute;right: 0;"> </span></h2>
     		    </div>
     		    
    </section>
    <!-- Main content -->
    <section class="content">	
	<div class="row">
	
		<div class="col-md-12">
			<div class="box box-success">
			      <div class="box-header" style="padding:0px;">
              
              <div class="box-tools pull-right">
                
              </div>
            </div>
				<div class="col-md-12">				
					@if ( session()->has('success') )
                    <div class="alert alert-success alert-dismissable">{{ session()->get('success') }}</div>
                     @endif
                    @if ( session()->has('error') )
                   <div class="alert alert-danger alert-dismissable">{{ session()->get('error') }}</div>
                    @endif  
					<div class="table-responsive">
						<table class="table table-hover table-bordered" id="example">
							<thead>
								<tr>
								    <th>#</th>
									<th width="9%">Date</th>
									
                                    <th width="28%">Type of Service</th>
                                    <th width="20%">Name</th>
									<th>New Business</th>	
									<th width="11%">Telephone</th>
									<th width="10%">Action</th>
								</tr>
							</thead>
							<tbody>
							    <?php $cnt=0;?>
							@foreach($applyservice as $employ)
							<?php $cnt++;//echo "<pre>";print_r($employ);?>
							<tr>
							    <td><?php echo $cnt;?></td>
									<td style="text-align:center;">{{date("M-d-Y", strtotime($employ->created_at))}}</td>
									<td>{{$employ->typeofcorp}}</td>
                                   
                                    <td>{{$employ->fname}} {{$employ->mname}} {{$employ->lname}}</td>
									
									
									

									<td>@if($employ->newbusiness != ''){{$employ->newbusiness}}@else --/-- @endif</td>	
									<td>{{$employ->phonenumber}}</td>
									<td style="text-align:center;">
                                        @if($employ->sign==1)<a class="" href="{{route('servicesprocess.edit',$employ->id)}}"><img src="{{asset('public/dashboard/images/newimage.gif')}}" alt="" width="42px"></a><br>@endif
                                        
                                        
                                        <a class="btn-action btn-view-edit" href="{{route('servicesprocess.edit', $employ->id)}}"><i class="fa fa-edit"></i></a>
                                        <form action="{{ route('servicesprocess.destroy',$employ->id) }}" method="post" style="display:none" id="delete-id-{{$employ->id}}">
                                        {{csrf_field()}} {{method_field('DELETE')}}
                                        </form>
                                        
										<a class="btn-action btn-delete" onclick="if(confirm('Are you sure, You want to delete this record ?'))
                                                                                  {event.preventDefault();document.getElementById('delete-id-{{$employ->id}}').submit();} else{event.preventDefault();}" href=""><i class="fa fa-trash"></i></a></td>
								</tr>
								@endforeach
                             </tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
		
	</div>
		</section>
</div>

<script>
$(document).ready(function() {
    var table = $('#example').DataTable( {
        dom: 'Bfrtlip',
    "columnDefs": [ {
            "searchable": true,
            "orderable": true,
            "targets": 0
        } ],
        "order": [[ 0, 'asc' ]],
        buttons: [
                 {
                extend:    'copyHtml5',
                text:      '<i class="fa fa-files-o"></i> &nbsp; Copy',
                titleAttr: 'Copy',
                title: $('h3').text(),
                  exportOptions: {
        columns: [0,1, 2, 3,4,5], // Only name, email and role
    }
            },
            {
                extend:    'excelHtml5',
                text:      '<i class="fa fa-file-excel-o"></i>&nbsp; Excel',
               titleAttr: 'Excel',
                title: $('h3').text(),
                 customize: function( xlsx ) {
                var sheet = xlsx.xl.worksheets['sheet1.xml'];
 $('row c', sheet).attr('s', '51');
            },
                  exportOptions: {
        columns: [0,1, 2, 3,4,5], // Only name, email and role
    }
            },
            {
                extend:    'csvHtml5',
                text:      '<i class="fa fa-file-text-o"></i> &nbsp; CSV',
                titleAttr: 'CSV',
                title: $('h3').text(),
                  exportOptions: {
        columns: [0,1, 2, 3,4,5], // Only name, email and role
    }
            },
            {
                extend:    'pdfHtml5',
                text:      '<i class="fa fa-file-pdf-o"></i>&nbsp;  PDF',
                
              customize: function (doc) {
						//Remove the title created by datatTables
						doc.content.splice(0,1);
						//Create a date string that we use in the footer. Format is dd-mm-yyyy
						var now = new Date();
						var jsDate = now.getDate()+'-'+(now.getMonth()+1)+'-'+now.getFullYear();
						var logo = 'data:image/jpeg;base64,{{$logo->logourl}}';
						doc.pageMargins = [20,60,20,20];
						doc.defaultStyle.fontSize = 10;
						doc.styles.tableHeader.fontSize = 10;
						doc['header']=(function() {
							return {
								columns: [{
									    alignment: 'left',
										image: logo,
										width: 50,margin: [200,5]
									},{
										alignment: 'CENTER',
										text: 'List of Client',
										fontSize: 20,
										margin: [10,35],
									},],
								margin: [20, 0, 0,12],alignment: 'center',
							}
						});
						var objLayout = {};
						objLayout['hLineWidth'] = function(i) { return 2; };
						objLayout['vLineWidth'] = function(i) { return 2; };
						objLayout['hLineColor'] = function(i) { return '#ccc'; };
						objLayout['vLineColor'] = function(i) { return '#ccc'; };
						objLayout['paddingLeft'] = function(i) { return 14; };
						objLayout['paddingRight'] = function(i) { return 14; };
						doc.content[0].layout = objLayout;
				},
				titleAttr: 'PDF',
                  exportOptions: {
        columns: [0,1, 2, 3,4,5], // Only name, email and role
    }
            },
            {
           extend: 'print',
          text: '<i class="fa fa-print"></i>&nbsp; Print',
          titleAttr: 'Print',
        customize: function ( win ) {
                    $(win.document.body)
                        .css( 'font-size', '10pt' )
                        .prepend(
                            '<center><img src="https://financialservicecenter.net/public/business/{{$logo->logo}}"/></center>'
                        );
                    $(win.document.body).find( 'table' )
                        .addClass( 'compact' )
                        .css( 'font-size', 'inherit' );
                },
         exportOptions: {
          columns: [0,1, 2, 3,4,5]
      },
      footer: true,
      autoPrint: true
    },],
    } );
$('input.global_filter').on( 'keyup click', function () {
        filterGlobal();
    } );
 
    $('input.column_filter').on( 'keyup click', function () {
        filterColumn( $(this).parents('tr').attr('data-column') );
    } );
  table.on( 'order.dt search.dt', function () {
       table.column(0, {search:'applied', order:'applied'}).nodes().each( function (cell, i) {
          cell.innerHTML = i + 1;
          table.cell(cell).invalidate('dom'); 
       } );
    } ).draw();
       table.columns(6)
        .search('^(?:(?!Inactive|New|1).)*$\r?\n?', true, false)
        .draw();
    $("#choice").on("change",function(){
 var _val = $(this).val();//alert(_val);
 
 if(_val == 'Inactive'){   
        table.columns(6).search(_val).draw();
  }
 else if(_val == 'New'){   
        table.columns(6).search(_val).draw();
  }
  else if(_val == 'Active'){  //alert();
         table.columns(6).search(_val).draw();
          table.columns(6)
        .search('^(?:(?!Inactive|New|1).)*$\r?\n?', true, false)
        .draw();
  }
  else{
        table
        .columns()
        .search('')
        .draw(); 
  }
  })
} );
   	</script>
	
@endsection()